#!/command/with-contenv bash

# many tools default to using the home directory for runtime data.
# as we mount a PVC to the home directory, these files might have the wrong permissions.
# to avoid this, we set the runtime directory to a path that is NOT a persistent volume.

echo "INFO: starting code-server..."
if [ "${DISABLE_COPILOT_EXTENSIONS:-true}" = "true" ] && [ -d "${HOME}/.local/share/code-server/extensions" ]; then
  find "${HOME}/.local/share/code-server/extensions" -maxdepth 1 -mindepth 1 \
    \( -iname "github.copilot*" -o -iname "github.copilot-chat*" \) \
    -exec rm -rf {} +
fi

exec 2>&1
exec /usr/bin/code-server \
  --bind-addr 0.0.0.0:8888 \
  --disable-telemetry \
  --disable-update-check \
  --disable-workspace-trust \
  --disable-getting-started-override \
  --auth none \
  --trusted-origins "*" \
  "${HOME}"
